### ISSUE TITLE
Queue Activating when 28-32 Players in Server (sv_maxclients 120)

### ISSUE THREAD

**Issue by Stephenlikewh0a** [JaredScar/Bad-DiscordQueue#10]
After configuring, 28-32 players are able to join my RedM server even though the sv_maxclients is set to 120. I have tried to wrap my head around what is locking up the queue. My work around is that I have to restart the queue script about a minute after my server restarts and it goes of course higher than 28-32 players.

Any tips or maybe I'm something I'm missing?

**Comment by JaredScar** [comment]
Make sure the script is started AFTER `sv_maxclients` is set
