### ISSUE TITLE
Stuck in ¨You are being connected¨

### ISSUE THREAD

**Issue by DmACKGL** [JaredScar/Bad-DiscordQueue#8]
I'm stuck here, the queue doesn't move at all.

![image](https://user-images.githubusercontent.com/10565361/89820740-7b73ad80-db1b-11ea-9d83-06073bef8f50.png)

**Comment by WayfaringCookie** [comment]
We also had a number of reports of the same. Had to revert back to another queue until a fix is sorted.

**Comment by JaredScar** [comment]
Do you have a Discord? I'd like to fully patch this script up, but don't really have anybody with the server capacity to fully test it. Please join my developer Discord and contact me there so we can patch this up. Sorry for the late reply, just saw this. 

Best Regards,
JaredScar

**Comment by JaredScar** [comment]
This has been fixed, thanks for reporting.

**Comment by kobel240** [comment]
Still not fixed buddy, tried it and I'm still stuck
