### ISSUE TITLE
allowing people to enter

### ISSUE THREAD

**Issue by hugochugo** [JaredScar/Bad-DiscordQueue#9]
Hello, the queue is still allowing people after 64. Seemed to be doing good and held people at 64 and with 5 in the queue. Then all of a sudden it let the whole queue through. I found no errors so can't really help. This is with latest version.

**Comment by JaredScar** [comment]
Can you provide your configuration?

**Comment by hugochugo** [comment]
took some info out

`Config = {
	Default_Prio = 500000, -- This is the default priority value if a discord isn't found
	AllowedPerTick = 1, -- How many players should we allow to connect at a time?
	HostDisplayQueue = true,
	onlyActiveWhenFull = true,
	Requirements = { -- A player must have the identifier to be allowed into the server
		Discord = true,
		Steam = true
	},
	WhitelistRequired = false, -- If this option is set to true, a player must have a role in Config.Rankings to be allowed into the server
	Debug = false,
	Webhook = '',
	Displays = {
		Prefix = '[BadgerDiscordQueue]',
		ConnectingLoop = { 
			'🦡🌿🦡🌿🦡🌿',
			'🌿🦡🌿🦡🌿🦡',
			'🦡🌿🦡🌿🦡🥦',
			'🌿🦡🌿🦡🥦🦡',
			'🦡🌿🦡🥦🦡🥦',
			'🌿🦡🥦🦡🥦🦡',
			'🦡🥦🦡🥦🦡🥦',
			'🥦🦡🥦🦡🥦🦡',
			'🦡🥦🦡🥦🦡🌿',
			'🥦🦡🥦🦡🌿🦡',
			'🦡🥦🦡🌿🦡🌿',
			'🥦🦡🌿🦡🌿🦡',
		},
		Messages = {
			MSG_CONNECTING = 'You are being connected [{QUEUE_NUM}/{QUEUE_MAX}]: ', -- Default message if they have no discord roles 
			MSG_CONNECTED = 'You are up! You are being connected now :)',
			MSG_DISCORD_REQUIRED = 'Your Discord was not detected... You are required to have Discord to play on this server...',
			MSG_STEAM_REQUIRED = 'Your Steam was not detected... You are required to have Steam to play on this server...',
			MSG_NOT_WHITELISTED = 'You do not have a Discord role whitelisted for this server... You are not whitelisted.',
		},
	},
}

Config.Rankings = {
	-- LOWER NUMBER === HIGHER PRIORITY 
	-- ['roleID'] = {rolePriority, connectQueueMessage},
	[''] = {600, "You are being connected (TOS Verified) [{QUEUE_NUM}/{QUEUE_MAX}]:"},
	[''] = {500, "You are being connected (Civilians) [{QUEUE_NUM}/{QUEUE_MAX}]:"},
	[''] = {400, "You are being connected (Server Booster) [{QUEUE_NUM}/{QUEUE_MAX}]:"},
	[''] = {350, "You are being connected (EMS) [{QUEUE_NUM}/{QUEUE_MAX}]:"},
	[''] = {300, "You are being connected (Police) [{QUEUE_NUM}/{QUEUE_MAX}]:"},
	--[''] = {200, "You are being connected (Patreon Tier 1) [{QUEUE_NUM}/{QUEUE_MAX}]:"}, 
	--[''] = {100, "You are being connected (Patreon Tier 2) [{QUEUE_NUM}/{QUEUE_MAX}]:"},
	[''] = {50, "You are being connected (Patreon Tier 3) [{QUEUE_NUM}/{QUEUE_MAX}]:"},
	[''] = {2, "You are being connected (Staff - Mod) [{QUEUE_NUM}/{QUEUE_MAX}]:"},
	[''] = {1, "You are being connected (Staff - Admin) [{QUEUE_NUM}/{QUEUE_MAX}]:"},
}`

**Comment by JaredScar** [comment]
I suggest turning on debug. This works fine for several other servers, so this may just be an issue on your end. You should make sure this resource is started after the max clients is declared.

**Comment by hugochugo** [comment]
I'll try putting the debug on. The order I have is maxclients before I start any resources then I have Badger_Discord_API started right after the essential esx resources then I have the discordqueue as last resource started. Could it be because of the hardcap resource am I supposed to not start it?

**Comment by JaredScar** [comment]
Do you have a Discord?
